#!/usr/bin/env bash
set -e

CONFIG_PATH=/data/options.json
SMARTPLUG_CONFIG=/data/smartplug/smartplug.yaml

echo "SmartPlug Controller - Home Assistant Add-on"
echo "============================================="

# Read options from Home Assistant
SENSOR_NODE_IDS=$(jq -r '.sensor_node_ids | join(",")' $CONFIG_PATH)
ACTUATOR_TYPE=$(jq -r '.actuator_type' $CONFIG_PATH)
DATA_TIMEOUT=$(jq -r '.data_timeout' $CONFIG_PATH)
START_THRESHOLD=$(jq -r '.start_threshold' $CONFIG_PATH)
STOP_THRESHOLD=$(jq -r '.stop_threshold' $CONFIG_PATH)
MAX_RUNTIME=$(jq -r '.max_runtime_minutes' $CONFIG_PATH)
COOLDOWN=$(jq -r '.cooldown_minutes' $CONFIG_PATH)
SCHEDULE_ENABLED=$(jq -r '.schedule_enabled' $CONFIG_PATH)
HA_DISCOVERY=$(jq -r '.ha_discovery' $CONFIG_PATH)
LOG_LEVEL=$(jq -r '.log_level' $CONFIG_PATH)

# Get MQTT credentials from Home Assistant services
MQTT_HOST="${MQTT_HOST:-core-mosquitto}"
MQTT_PORT="${MQTT_PORT:-1883}"
MQTT_USER="${MQTT_USERNAME:-}"
MQTT_PASS="${MQTT_PASSWORD:-}"

echo "Configuration:"
echo "  Sensor nodes: ${SENSOR_NODE_IDS}"
echo "  Actuator type: ${ACTUATOR_TYPE}"
echo "  MQTT broker: ${MQTT_HOST}:${MQTT_PORT}"

# Convert comma-separated node IDs to YAML array
IFS=',' read -ra NODES <<< "$SENSOR_NODE_IDS"
NODE_YAML=""
for node in "${NODES[@]}"; do
    NODE_YAML="${NODE_YAML}    - \"${node}\"\n"
done

# Generate SmartPlug configuration file
cat > $SMARTPLUG_CONFIG << EOF
# Auto-generated by Home Assistant Add-on
# Do not edit - changes will be overwritten on restart

deployment:
  mode: controller
  sensor_node_ids:
$(echo -e "$NODE_YAML")  actuator_type: ${ACTUATOR_TYPE}
  data_timeout: ${DATA_TIMEOUT}

pump:
  start_threshold: ${START_THRESHOLD}
  stop_threshold: ${STOP_THRESHOLD}
  max_runtime_minutes: ${MAX_RUNTIME}
  cooldown_minutes: ${COOLDOWN}
  min_temperature: 40.0

schedule:
  enabled: ${SCHEDULE_ENABLED}
  slots: []
  learning:
    enabled: true
    min_days: 7
    vacation_timeout_hours: 24

web:
  address: ":8080"

mqtt:
  enabled: true
  broker: "tcp://${MQTT_HOST}:${MQTT_PORT}"
  username: "${MQTT_USER}"
  password: "${MQTT_PASS}"
  topic_prefix: "smartplug"
  ha_discovery: ${HA_DISCOVERY}
  ha_discovery_prefix: "homeassistant"

logging:
  level: "${LOG_LEVEL}"

system:
  data_dir: "/data/smartplug"
EOF

echo "Generated config at ${SMARTPLUG_CONFIG}"
echo "Starting SmartPlug Controller..."

# Start the controller
exec /usr/local/bin/smartplug-controller --config $SMARTPLUG_CONFIG
